on: [push, pull_request]

name: tests

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        tc: [beta, nightly]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --all-features
  cross-compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [1.70.0]
        cc:
        - aarch64-linux-android
        - i686-pc-windows-gnu
        - i686-unknown-freebsd
        - i686-unknown-linux-gnu
        - wasm32-unknown-unknown
        - x86_64-apple-darwin
        - x86_64-unknown-redox
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features --target=${{ matrix.cc }}
  cross-compile-ios:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        tc: [1.70.0]
        cc: [aarch64-apple-ios]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features --target=${{ matrix.cc }}
